name: block-pipline
on:
  workflow_dispatch:
    inputs:
      target_enviornment:
        description: "TEMP desired enviornment project will be promoted to."
        type: string
        required: true
      feature_name:
        description: "Directory name where files to be checked "
        type: string
        required: true
jobs:
  check-enviornment:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download jq library
        run: sudo apt-get install jq

      - name: Give permission
        run: chmod +x .github/workflows/verify_annotation.sh

      #TODO: TAKE OUT SPECIFYING DIRECTORY
      - name: TEMP NAME
        run: .github/workflows/verify_annotation.sh ${{ inputs.target_enviornment }} ${{ inputs.feature_name }}
      - name: Set user
        run: git config --global user.name "${{ github.actor }}"
      - name: Set email
        run: git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      #- name: Stage changes
      #  run: git add --all
      #- name: Commit changes
      #  run: git commit -m "Removed any unallowed pipelines."
      #- name: Push origin
      #  run: git push -u origin #INSERT NAME OF CURRENT BRANCH