name: block-pipline
on:
  workflow_dispatch:
jobs:
  check-enviornment:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Give permissions
        run: chmod +x .github/workflows/verify_annotation.sh
      - name: Verify which features have annotations
        run: .github/workflows/verify_annotation.sh Approved
      - name: Set user
        run: git config --global user.name "${{ github.actor }}"
      - name: Set email
        run: git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
      - name: Stage changes
        run: git add --all
      - name: Commit changes
        run: git commit -m "Exlcuded files not associated with a pipeline ready for prod."
      - name: Push origin
        run: git push -u origin